server:
  port: 8082
spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3306/order?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect


eureka:
  instance:
    hostname: 127.0.0.1
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:7002/eureka/
seata:
  enabled: true
  tx-service-group: laiyuezs_tx_group                            # 事务组
  registry:
    type: eureka
    eureka:
      service-url: http://${eureka.instance.hostname}:7002/eureka/
  service:
    vgroup-mapping:
      laiyuezs_tx_group : seata-server
    enable-degrade: false                                 # 降级开关
    disable-global-transaction: false                   # 禁用全局事务（默认false）
  client:
    rm:
      report-success-enable: true
      table-meta-check-enable: false                     # 自动刷新缓存中的表结构（默认false）
      report-retry-count: 5                               # 一阶段结果上报TC重试次数（默认5）
      async-commit-buffer-limit: 10000                   # 异步提交缓存队列长度（默认10000）
      lock:
        retry-interval: 10                                 # 校验或占用全局锁重试间隔（默认10ms）
        retry-times: 30                                    # 校验或占用全局锁重试次数（默认30）
        retry-policy-branch-rollback-on-conflict: true   # 分支事务与其它全局回滚事务冲突时锁策略（优先释放本地锁让回滚成功）
    tm:
      commit-retry-count: 3                                # 一阶段全局提交结果上报TC重试次数（默认1次，建议大于1）
      rollback-retry-count: 3                              # 一阶段全局回滚结果上报TC重试次数（默认1次，建议大于1）

    undo:
      data-validation: true                                # 二阶段回滚镜像校验（默认true开启）
      log-serialization: jackson                            # undo序列化方式（默认jackson）
      log-table: undo_log                                    # 自定义undo表名（默认undo_log）
    log:
      exception-rate: 100                                    # 日志异常输出概率（默认100）