server:
  port: 8081
spring:
  application:
    name: storage-service
  datasource:
    url: jdbc:mysql://localhost:3306/storage?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  cloud:
    alibaba:
      seata:
        tx-service-group: laiyuezs_tx_group
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:7002/eureka/